/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

/**
 *
 * @author mathe
 */
public class Calculadora_ extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora_.class.getName());

    /**
     * Creates new form Calculadora_
     */
    int NumEnter1;
    int NumEnter2;
    int Resultado;
    String Op;
    private boolean resultadoMostrado = false;
    
    public Calculadora_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextResultado = new javax.swing.JTextField();
        jButtonCE = new javax.swing.JButton();
        jButtonBS = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonTimes = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextResultado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 410, 80));

        jButtonCE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonCE.setText("CE");
        jButtonCE.addActionListener(this::jButtonCEActionPerformed);
        getContentPane().add(jButtonCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, 80));

        jButtonBS.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButtonBS.setText("<-");
        jButtonBS.addActionListener(this::jButtonBSActionPerformed);
        getContentPane().add(jButtonBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 80, 80));

        jButtonC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(this::jButtonCActionPerformed);
        getContentPane().add(jButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, 80));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(this::jButton8ActionPerformed);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 80, 80));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(this::jButton7ActionPerformed);
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 80));

        jButtonPlus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(this::jButtonPlusActionPerformed);
        getContentPane().add(jButtonPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 80, 80));

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(this::jButton9ActionPerformed);
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 80, 80));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 80, 80));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 80, 80));

        jButtonMinus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(this::jButtonMinusActionPerformed);
        getContentPane().add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 80, 80));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(this::jButton6ActionPerformed);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 80, 80));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 80, 80));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 80, 80));

        jButtonTimes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonTimes.setText("*");
        jButtonTimes.addActionListener(this::jButtonTimesActionPerformed);
        getContentPane().add(jButtonTimes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 80, 80));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 80, 80));

        jButton0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(this::jButton0ActionPerformed);
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 80, 80));

        jButtonDiv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.addActionListener(this::jButtonDivActionPerformed);
        getContentPane().add(jButtonDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 80, 80));

        jButtonIgual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(this::jButtonIgualActionPerformed);
        getContentPane().add(jButtonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void EntradaNum(String q){
        if (resultadoMostrado) {
        jTextResultado.setText(""); 
        resultadoMostrado = false;  
    }
        String Nums = jTextResultado.getText() + q;
        jTextResultado.setText(Nums);
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        EntradaNum("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        EntradaNum("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        EntradaNum("9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EntradaNum("4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        EntradaNum("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        EntradaNum("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EntradaNum("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EntradaNum("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EntradaNum("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        EntradaNum("0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        NumEnter1 = Integer.parseInt(jTextResultado.getText());
        jTextResultado.setText(jTextResultado.getText() + " / ");
        Op ="/";
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimesActionPerformed
        NumEnter1 = Integer.parseInt(jTextResultado.getText());
        jTextResultado.setText(jTextResultado.getText() + " * ");
        Op ="*";
    }//GEN-LAST:event_jButtonTimesActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        NumEnter1 = Integer.parseInt(jTextResultado.getText());
        jTextResultado.setText(jTextResultado.getText() + " - ");
        Op ="-";
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        NumEnter1 = Integer.parseInt(jTextResultado.getText());
        jTextResultado.setText(jTextResultado.getText() + " + ");
        Op ="+";
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jTextResultado.setText("");
         NumEnter1 = 0;
        NumEnter2 = 0;
        Op = "";
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCEActionPerformed
        jTextResultado.setText("");
        
        String Pn, Sn;
        
        Pn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Pn="";
        Sn="";
    }//GEN-LAST:event_jButtonCEActionPerformed

    private void jButtonBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBSActionPerformed
        String backS = null;
        
        if (jTextResultado.getText().length() > 0){
            StringBuilder sb = new StringBuilder(jTextResultado.getText());
            sb.deleteCharAt(jTextResultado.getText().length() -1);
            backS = sb.toString();
            jTextResultado.setText (backS);
        }
    }//GEN-LAST:event_jButtonBSActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        String[] partes = jTextResultado.getText().split("[+\\-*/]");
        NumEnter2 = Integer.parseInt(partes[partes.length - 1].trim());
        
        if(Op.equals ("+")){
            Resultado = NumEnter1 + NumEnter2;
            jTextResultado.setText(String.valueOf(Resultado));
        }
        else if(Op.equals ("-")){
            Resultado = NumEnter1 - NumEnter2;
            jTextResultado.setText(String.valueOf(Resultado));
        }
        else if(Op.equals ("/")){
            Resultado = NumEnter1 / NumEnter2;
            jTextResultado.setText(String.valueOf(Resultado));
        }
        else{
            Resultado = NumEnter1 * NumEnter2;
            jTextResultado.setText(String.valueOf(Resultado));
        }
        jTextResultado.setText(String.valueOf(Resultado));
        resultadoMostrado = true;
    }//GEN-LAST:event_jButtonIgualActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora_().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBS;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCE;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonTimes;
    private javax.swing.JTextField jTextResultado;
    // End of variables declaration//GEN-END:variables
}
